name: 16 - Working with Environments
run-name: 16 - Working with Enviroments - ${{ github.event.inputs.target-env }}
on:
  workflow_dispatch:
    inputs:
        target-env:
          description: 'Target environment to deploy to'
          type: environment
          default: 'staging'
jobs:
  echo:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.target-env }}
    env:
      my-env-value: ${{ vars.MY_ENV_VALUE }} || 'default-value'
    steps:
    - name: Echo environment value
      run: echo ${{ env.my-env-value }}