name: 19 - 2 - Managing Concurrency

on:
  workflow_dispatch:

jobs:
  ping-with-concurrency:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Ping
        run: |
          echo "Pinging"
          sleep 10
  ping-without-concurrency:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Ping
        run: |
          echo "Pinging"
          sleep 10